import argparse
import os

import torch
from PIL import Image

from modules import (
    StyleEncoder,
    LUTGenerator,
    create_identity_lut,
)
from preprocess import build_style_transform


def parse_args():
    p = argparse.ArgumentParser(description="Export 3D LUT (.cube) from a style image")
    p.add_argument("--ckpt", type=str, required=True, help="Path to checkpoint .pth")
    p.add_argument("--style", type=str, required=True, help="Path to style image")
    p.add_argument("--lut_path", type=str, required=True, help="Output .cube path")
    p.add_argument("--device", type=str, default="cuda")
    p.add_argument("--image_size", type=int, default=256)
    return p.parse_args()


def load_style(path, size, style_norm):
    tfm = build_style_transform(size, style_norm)
    img = Image.open(path).convert("RGB")
    return tfm(img).unsqueeze(0)  # [1,3,H,W]


def save_cube_lut(lut: torch.Tensor, path: str):
    """
    lut: [N,N,N,3], values in [0,1]
    Save in a simple .cube file format.
    """
    N = lut.shape[0]
    lut_np = lut.detach().cpu().numpy().reshape(-1, 3)

    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write("# Generated by LUT-GAN\n")
        f.write("LUT_3D_SIZE {}\n".format(N))
        for r, g, b in lut_np:
            f.write(f"{r:.6f} {g:.6f} {b:.6f}\n")
    print("Saved LUT to", path)


def main():
    args = parse_args()
    device = args.device if torch.cuda.is_available() else "cpu"

    ckpt = torch.load(args.ckpt, map_location=device)
    ckpt_args = ckpt["args"]
    lut_size = ckpt_args["lut_size"]
    latent_dim = ckpt_args["latent_dim"]
    encoder_arch = ckpt_args.get("encoder_arch", "resnet18")
    delta_scale = ckpt_args.get("delta_scale", 0.1)
    zero_mean = ckpt_args.get("zero_mean", True)
    style_norm = ckpt_args.get("style_norm", "none")

    identity_lut = create_identity_lut(lut_size, device=device)

    encoder = StyleEncoder(latent_dim=latent_dim, arch=encoder_arch)
    generator = LUTGenerator(latent_dim=latent_dim, size=lut_size, delta_scale=delta_scale, zero_mean=zero_mean)

    encoder.load_state_dict(ckpt["encoder"])
    generator.load_state_dict(ckpt["generator"])

    encoder.to(device).eval()
    generator.to(device).eval()

    style_img = load_style(args.style, size=args.image_size, style_norm=style_norm).to(device)

    with torch.no_grad():
        z = encoder(style_img)
        lut_batch = generator(z, identity_lut)  # [1,N,N,N,3]

    lut = lut_batch[0]  # [N,N,N,3]
    save_cube_lut(lut, args.lut_path)


if __name__ == "__main__":
    main()
